// Generated by CoffeeScript 1.6.2
(function() {
  var CLIENT_ID, CLIENT_SECRET, OAuth2Client, REDIRECT_URL, googleapis;

  googleapis = require('googleapis');

  OAuth2Client = googleapis.OAuth2Client;

  console.log(OAuth2Client);

  CLIENT_ID = '998322373435.apps.googleusercontent.com';

  CLIENT_SECRET = 'U8QgUx2ygHzI-n5txUPMgcYV';

  REDIRECT_URL = 'http://localhost/oauth2callback';

  googleapis.discover('plus', 'v1').execute(function(err, client) {
    var oauth2Client;

    oauth2Client = new OAuth2Client(CLIENT_ID, CLIENT_SECRET, REDIRECT_URL);
    return console.dir(oauth2Client);
  });

}).call(this);

/*
//@ sourceMappingURL=auth.map
*/
