// Generated by CoffeeScript 1.6.2
/* MongoHQ Test
*/


(function() {
  var Schema, db, mongoose, msg;

  db = require('./config/db');

  mongoose = require('mongoose');

  mongoose.connect('mongodb://' + db.user + ':' + db.pass + '@' + db.host + ':' + db.port + '/' + db.name);

  Schema = mongoose.Schema;

  msg = new Schema({
    m: String,
    n: String,
    t: Number,
    p: String
  });

  mongoose.model('msg', msg);

}).call(this);
