CREATE TABLE IF NOT EXISTS people (
  id SERIAL PRIMARY KEY,
  email VARCHAR(254) UNIQUE NOT NULL,
  firstname VARCHAR(100) DEFAULT NULL,
  lastname VARCHAR(100) DEFAULT NULL,
  password VARCHAR(60) NOT NULL,
  joined INTEGER DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP),
  confirmed INTEGER DEFAULT null
);
